### ISSUE TITLE
Fails to connect / Unexpected error

### ISSUE THREAD

**Issue by mr-biz** [meichthys/uptime_kuma#10]
Hello,
I was following this tutorial: https://www.youtube.com/watch?v=9xBGO2Fpnkc
I got to configuring the integration in Home Assitant.
![image](https://user-images.githubusercontent.com/44796116/187312772-105f81c0-6120-4311-9d3f-4ee59aeab1ff.png)

Error message received:  Failed to connect
<img width="227" alt="image" src="https://user-images.githubusercontent.com/44796116/187313086-0e31cb4a-486f-4508-9ecc-6b22fb80b30c.png">

Many thanks in advance for your help.

**Comment by m1ckyb** [comment]
The URL needs to be the full url with http://host:PORT/ or https://host/

**Comment by mr-biz** [comment]
So in the case of http I should use  http://host:PORT/ or http://192.168.1.33:3001/
In that case, I get an "Unexpected error".
![image](https://user-images.githubusercontent.com/44796116/187364368-3b5f9daa-129e-4e73-b686-ab48aa7d5ee0.png)

**Comment by mr-biz** [comment]
So in the case of http I should use http://host:PORT/ or http://192.168.1.33:3001/
In that case, I get an "Unexpected error".
<img width="226" alt="image" src="https://user-images.githubusercontent.com/44796116/187364857-da29d905-6295-40f5-9773-1a2450083668.png">

**Comment by meichthys** [comment]
How are you running Uptime Kuma? Via the homeassistant addon? Are you able to log in to UptimeKuma?

**Comment by mr-biz** [comment]
I am running Uptime Kuma via the HA addon.
I am able to log in to Uptime Kuma.
![image](https://user-images.githubusercontent.com/44796116/187418751-192f6aa7-2847-44ac-9ca7-1284b7577e48.png)

![image](https://user-images.githubusercontent.com/44796116/187418773-e4c563af-7c2c-4aff-a554-cba1d2764ec8.png)

**Comment by meichthys** [comment]
I don't think you need to enter the port in the URL and also in the port field. Try removing the port number from the URL.

**Comment by mr-biz** [comment]
If I put http://192.168.1.33/ I get "Failed to connect"

**Comment by m1ckyb** [comment]
Are you using the right user name and password?

I added the home assistant add on, and configured it as below and it worked.

![Screenshot_20220830-225237.png](https://user-images.githubusercontent.com/6329363/187442675-b7a7b4b6-2efa-4fc0-aabb-e9651d40d3f4.png)

**Comment by mr-biz** [comment]
I changed my password and it works!
Thank you for your help!

**Comment by mr-biz** [comment]
Where is the beer token button?!
