### ISSUE TITLE
Push monitors not appearing in hass

### ISSUE THREAD

**Issue by meanmrgreen** [meichthys/uptime_kuma#13]
The passive monitor type "Push" is not appearing in the integration list of sensors only active polling ones.
Ping/HTTP and such are working fine

version of uptimekuma hosted on another machine: `1.17.1`
version of this integration used: `1.2.0`

**Comment by meichthys** [comment]
Please check your configurations. This should work:
![image](https://user-images.githubusercontent.com/10717998/204122298-17723543-626a-48e7-9592-430675134ec9.png)
(Note the `monitor_type`
