### ISSUE TITLE
Submit to HACS store

### ISSUE THREAD

**Issue by meichthys** [meichthys/uptime_kuma#16]

**Comment by meichthys** [comment]
@tjorim Any idea why this if failing?
https://github.com/hacs/default/actions/runs/3231795429/jobs/5291701038

**Comment by tjorim** [comment]
https://github.com/hacs/default/pull/1537#discussion_r993064490

**Comment by a73x3434** [comment]
hey, first cool project. Quick question, what's the current status?

**Comment by meichthys** [comment]
It's pending. It needs 3 code reviews:
https://github.com/hacs/default/pull/1538

**Comment by tjorim** [comment]
This issue can be closed, should be present in the HACS store by default now.

**Comment by hugalafutro** [comment]
so what's the procedure for switching form manual install to hacs install, just remove and install form hacs again ?
