### ISSUE TITLE
UI hangs and errors when adding integration

### ISSUE THREAD

**Issue by djahren** [meichthys/uptime_kuma#18]
After selecting Uptime Kuma from the Add Integrations menu it sits there hanging for about a minute or two and finally errors out with the following message: 
```Config flow could not be loaded: <html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> <hr><center>nginx</center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->```

This error may be unique to my environment as the error mentions nginx and I use that as my reverse proxy. To test this theory I tried doing the same steps when connected directly to my home assistant instance - circumnavigating nginx. The symptoms were the same, the only difference is that it's been sitting there for about 10 minutes now and is still spinning - it hasn't yet errored out. Doing the same thing (direct connection, no nginx) in an incognito window gave the same issue of the page loading indicator spinning indefinitely. While the nginx error may be unique to my setup, hopefully the `504 time-out` might lend a clue as to the source of the issue. 

Currently running HA Core 2022.11.2
Installed the uptime_kuma integration via HACS

**Comment by meichthys** [comment]
I haven't seen this yet. What version are you trying to install? 
V2.0.0 seems to be ok on my end.

**Comment by djahren** [comment]
Whichever is most current in HACS. It appears to be 2.0.0. I'll spin up a
brand new instance of HA to test it on later today.

**Comment by djahren** [comment]
Apologies for the delayed reply, it does appear to just be my setup that's causing issues as spinning up a new instance of home assistant allowed the uptimekuma config to finish. I am using nginxproxymanager so I'll attempt to mirror your settings and see if that works. Will close this out for now but will update if I find a solution so if anyone else comes across they same thing they can replicate.
