### ISSUE TITLE
Can we have nice brand icon for it?

### ISSUE THREAD

**Issue by ranrinc** [meichthys/uptime_kuma#2]
Anyway great work and loving it. It work like a charms. However its need brand icons on the integrations side. Hope this can be done. Again thanks

**Comment by JOHLC** [comment]
> Anyway great work and loving it. It work like a charms. However its need brand icons on the integrations side. Hope this can be done. Again thanks

This will require a merged pull request in the Home Assistant Brands repo 
There is already an open and approved request here: https://github.com/home-assistant/brands/pull/2937 
So I think we should see this soon once it gets merged. 

Dev: thanks for your work on this component
