### ISSUE TITLE
Readme needs more detail

### ISSUE THREAD

**Issue by jsnfwlr** [meichthys/uptime_kuma#20]
I use Uptime Kuma and Home Assistant, but I have no idea what functionality this integration will provide if I install and configure it.

While I could install it and set it up and then see what it does, it would be nice to know before I spend any time on it.

Additionally, we shouldnt be encouraging users to install and experiment with software or extensions they don't understand, so please update the README.md to include details of what this integration requires, what it provides, and examples of how it could be used.

**Comment by jsnfwlr** [comment]
I've looked through the code and can see it requires an instance of Uptime Kuma, and sets up sensors for the various monitors you have in Uptime Kuma. The sensors have three states - up, down, and pending - which is why a binary-sensor isn't used.

**Comment by meichthys** [comment]
Yes it should go without saying that you will need a uptime kuma and that it would create sensors that indicate the status of your uptime kuma monitors. 

I will try to get the readme updated when I get some time, but pull requests are also welcome. I mostly built this for myself - the HACS integration was added later by pull request.

**Comment by meichthys** [comment]
For reference this is how a monitor will be exposed in homeassistant:
![image](https://user-images.githubusercontent.com/10717998/203177002-f1c83a3b-9d94-40d4-9db3-fb1e108ea9ca.jpeg)
