### ISSUE TITLE
fails to work 

### ISSUE THREAD

**Issue by progamer562** [meichthys/uptime_kuma#22]
when i type my address and password it dosnt work no mater what i tryed the local ip and the domain nothing 

this is the logs that kuma spits out

2022-11-23 10:12:47.542 ERROR (MainThread) [custom_components.uptime_kuma] Request exception for 'kuma.#####der.com:443/metrics' with - kuma.#####der.com:443/metrics

**Comment by meichthys** [comment]
Are you putting the port on the url? You shouldn't need to. I'm had similar reports but haven't been able to reproduce any of them yet.

**Comment by progamer562** [comment]
it forceing me to do so

**Comment by mefisto22** [comment]
same issues here
Logger: custom_components.uptime_kuma
Source: custom_components/uptime_kuma/config_flow.py:78
Integration: Uptime Kuma
First occurred: 04:32:19 (1 occurrences)
Last logged: 04:32:19

Request exception for '192.168.12.12:3321/metrics' with - 192.168.12.12:3321/metrics

**Comment by meichthys** [comment]
@progamer562 & @mefisto22  Please provide a screenshot of your integration setup.
If you are behind a reverse proxy (I recommend this), then you would configure the integration like this:
![image](https://user-images.githubusercontent.com/10717998/204120111-9e4193df-8767-42c4-9b02-2504039065f4.png)

**Comment by progamer562** [comment]
> @progamer562 & @mefisto22 Please provide a screenshot of your integration setup. If you are behind a reverse proxy (I recommend this), then you would configure the integration like this: ![image](https://user-images.githubusercontent.com/10717998/204120111-9e4193df-8767-42c4-9b02-2504039065f4.png)

YAY this works thank you so much
