### ISSUE TITLE
Addon not working with the HA Uptime Kuma Addon

### ISSUE THREAD

**Issue by Kilowatt-W** [meichthys/uptime_kuma#23]
Hello there,

at the moment I cannot connect to my UptimeKuma Addon in HA becaus the addon of Fraenk only gets up with http instead of https.

What ever I tried in the Integration it looks like it always writes https infront of the Url so its not possible to use it togehter :-(

Maybe a config switch in the integration for "Use https" or not would be helpful

Greetings from Austria

Kilowatt

**Comment by m1ckyb** [comment]
Just set it up a addon on my host,

Setup as follows works:

Host: http://<address>Port: 3001 <or custom_port>

Uncheck Verify SSL cert

![2022-11-25 (4)](https://user-images.githubusercontent.com/6329363/203979012-12a40e50-0a5b-4b29-bf7d-6986b391ebbe.png)

**Comment by meichthys** [comment]
@Kilowatt-W Please uncheck the "Veify SSL certificate" option and check your dns configuration if you have a non-standard install of home assistant.
