### ISSUE TITLE
Impossible connect to UptimeKuma (Versión: 1.18.5)

### ISSUE THREAD

**Issue by jvcsw** [meichthys/uptime_kuma#25]
Hi,

I can't connect to Kuma using this integration:

![imagen](https://user-images.githubusercontent.com/37216513/207591676-19eebbed-ab98-446f-aee8-80e0513c9136.png)

Kuma is a local container without SSL.

Log: 

Logger: custom_components.uptime_kuma
Source: custom_components/uptime_kuma/config_flow.py:78
Integration: Uptime Kuma ([documentation](https://github.com/meichthys/uptime_kuma/blob/main/README.md), [issues](https://github.com/meichthys/uptime_kuma/issues))
First occurred: 12:49:17 (3 occurrences)
Last logged: 13:04:13
Request exception for 'x.x.x.x:7200/metrics' with - x.x.x.x:7200/metrics

I can see the metrics correctly: x.x.x.x:7200/metrics

Thanks

**Comment by meichthys** [comment]
https://github.com/meichthys/uptime_kuma/issues/23

**Comment by jvcsw** [comment]
Ok, sorry and thanks.
It's working.
