### ISSUE TITLE
Cannot connect to Uptime Kuma instance on port 3001

### ISSUE THREAD

**Issue by mzurhorst** [meichthys/uptime_kuma#27]
Hi all.

I have deployed Uptime Kuma in a Docker container on Port 3001 according to their documentation.
It works very well, but I do now have trouble to connect to this instance via the HomeAssistant integration.

In the log file, I see:
**Request exception for '192.168.10.118:3001/metrics' with - 192.168.10.118:3001/metrics** 

Logger: custom_components.uptime_kuma
Source: custom_components/uptime_kuma/config_flow.py:78
Integration: Uptime Kuma ([documentation](https://github.com/meichthys/uptime_kuma/blob/main/README.md), [issues](https://github.com/meichthys/uptime_kuma/issues))
First occurred: 19:27:06 (1 occurrences)
Last logged: 19:27:06

I can indeed open the above URL from my computer and the page loads as soon as I enter the credentials.
What is going wrong? - Is it that I am deviating from the proposed https port 443? -- Or anything else?

Thank you.

**Comment by m1ckyb** [comment]
See #23

**Comment by mzurhorst** [comment]
Thank you!!
