### ISSUE TITLE
Push monitors not working in ha

### ISSUE THREAD

**Issue by Cire2019** [meichthys/uptime_kuma#31]
Hello,
I installed this integration and it works fine for http, ping , tcp. Very easy to configure. Very nice integration
But when i try with push (monitor type), it appears in HA but disappears after few minutes

In the Kuma console, it is present and it's working fine, but not in HA

I'm using latest version 1.18.5 (on my HA instance) and 1.19.2 on another VM. Same issue with both installation

My HA  & HACS are up to date.

Any idea on how to solve this issue.

Thanks a lot

**Comment by meichthys** [comment]
Check to see if your monitor shows up in the UptimeKuma metrics endpoint:
https://<your_uptimekuma_url>/metrics

If it doesn't show up there, then it's a misconfiguration or bug on the UptimeKuma side.
In my testing, the push monitors seem to be a little finicky in the metrics endpoint. They seem to come and go.
Try re-creating the monitor.
