### ISSUE TITLE
called async_setup_platforms instead of awaiting async_forward_entry_setups

### ISSUE THREAD

**Issue by H4rl3k1n** [meichthys/uptime_kuma#34]
Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 07:08:25 (2 occurrences)
Last logged: 07:08:36
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for uptime_kuma using this method at custom_components/uptime_kuma/__init__.py, line 52: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

fyi

**Comment by meichthys** [comment]
This should be fixed in v2.0.3
