### ISSUE TITLE
[feature request] Toggle to create problem sensors instead of connectivity sensors

### ISSUE THREAD

**Issue by kekonn** [meichthys/uptime_kuma#35]
During set up, please allow a toggle to create problem sensors instead of connection sensors. 

This would mean switching out the device class and inverting the state of the binary sensor. Or you could choose to create both binary sensors per device and allow us to enable or disable one of sensors.

**Comment by meichthys** [comment]
Pull requests are welcome, but I don't think this is something o will add since you can filter out the sensors in homeassistant or use group sensors to do what you need:
![image](https://user-images.githubusercontent.com/10717998/216589310-3e13c3fa-6fac-4394-9d2e-6465f0eac8b7.jpeg)
