### ISSUE TITLE
Problems with HA 2023.03

### ISSUE THREAD

**Issue by lbandi2** [meichthys/uptime_kuma#38]
Upon installing the march version of HA i get this message in the log:

`Unable to install package pyuptimekuma==0.0.6: ERROR: Cannot install pyuptimekuma==0.0.6 because these package versions have conflicting dependencies. ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts [notice] A new release of pip is available: 23.0 -> 23.0.1 [notice] To update, run: pip install --upgrade pip`

And immediately afterwards:

`Setup failed for custom integration uptime_kuma: Requirements for uptime_kuma not found: ['pyuptimekuma==0.0.6']`

I wasn't having any problems so I figure it must be related to the new HA version. I'm willing to lend a hand however I can to solve this issue.

**Comment by m1ckyb** [comment]
See #37
