### ISSUE TITLE
Feature request: change entity name

### ISSUE THREAD

**Issue by poudenes** [meichthys/uptime_kuma#4]
Hi All,

Love this tool!!! Woudl be nice to see follow:

binary_sensor.<uptime kuma name>

to

binary_sensor.uptimekuma_<uptime kuma name>

When you have a lot of entities you can search for "uptimekuma" to see all the sensors.
Beside that. Its my opinion nicer to have the name inside the sensor entitiy name.

Cheers
Peter

**Comment by jayakornk** [comment]
Included in this PR https://github.com/meichthys/uptime_kuma/pull/5 with a couple more attributes. 😉

**Comment by poudenes** [comment]
Great!!! Love the new way. Love the new attributes!!!
