### ISSUE TITLE
Unable to add integration

### ISSUE THREAD

**Issue by C47hub** [meichthys/uptime_kuma#41]
When I try to add the integration I am unable to enter any data like the URL, it throws this error:
Fout
Config-flow kon niet geladen worden: 500 Internal Server Error Server got itself in trouble

**Comment by paulstride** [comment]
+1 - also seeing this..

_Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble_

**Comment by quinten94b** [comment]
+1 and no more details to find in logs on my end.

**Comment by quinten94b** [comment]
+1 and no more details to find in logs on my end.

running:
Home Assistant 2023.3.1
Supervisor 2023.01.1
Operating System 9.5
Frontend-versie: 20230302.0 - latest

**Comment by meichthys** [comment]
Most likely caused by https://github.com/meichthys/uptime_kuma/issues/37

**Comment by Haballama** [comment]
+1 also having this issue. Will keep an eye on this thread

**Comment by Laclan** [comment]
Reference from @meichthys 

This should now be patched in v2.1.0.
Please check HACS for the update and report back if you have any issues. If you don't see the update in HACS, try clicking 'Redownload' in the HACS menu:

![alt](https://user-images.githubusercontent.com/10717998/223921961-98e191a3-cf3a-4f2d-a6fa-ab366596ab52.png)
