### ISSUE TITLE
Push Passive Monitor not imported to Home Assistant

### ISSUE THREAD

**Issue by jorgemontes** [meichthys/uptime_kuma#52]
Hello,

I recently created a Passive Push monitor in UptimeKuma, then I went into Home Assistant to reload the Integration as I always do when I create a new one. The new `binary_sensor` was not present as a service or device.  After checking the log I find:
```
2023-05-23 20:48:30.908 DEBUG (MainThread) [custom_components.uptime_kuma] Finished fetching uptime_kuma data in 0.685 seconds (success: True)
```
Still no luck on this Monitor to show. 
Any Ideas?
thank you

**Comment by jorgemontes** [comment]
Maybe It can be moved to a Feature Request

**Comment by jorgemontes** [comment]
For my version of UptimeKuma, 1.21.3, the `/metrics` endpoint does not return that monitor. I wonder what is so different about it

**Comment by imjuzcy** [comment]
I updated to the 1.22 beta, it doesn't seem to be working yet.

**Comment by jorgemontes** [comment]
@meichthys , I updated to ` 1.22.1`  I see now being returned from `/metrics` endpoint
````
monitor_response_time{monitor_name="Wireguard",monitor_type="push",monitor_url="https://XXXXXXX",monitor_hostname="nico",monitor_port="XXXX"} -1
````
 and also being grabbed by the Integration too with type `push`
 
![image](https://github.com/meichthys/uptime_kuma/assets/6100028/9723567d-468e-4b0e-b662-498a5a148c52)

 
I think this one can be closed then
