### ISSUE TITLE
Sensors are getting down even in pending state

### ISSUE THREAD

**Issue by dibyadip-das** [meichthys/uptime_kuma#6]
Sensors should not be down during the pending state i.e. when retries are in progress. Only after the retires are completed, once the sensor in Uptime Kuma is declared as down should the HA sensor be down too.

**Comment by meichthys** [comment]
@jayakornk Could you also take a look at this if/when you get a chance?

**Comment by jayakornk** [comment]
> Sensors should not be down during the pending state i.e. when retries are in progress. Only after the retires are completed, once the sensor in Uptime Kuma is declared as down should the HA sensor be down too.

Which monitor type is this?

**Comment by jayakornk** [comment]
Wait for https://github.com/meichthys/uptime_kuma/pull/9 to merge and create new release (Integration v1.2.1)

**Comment by meichthys** [comment]
Merged and released in v1.2.0 👍
