### ISSUE TITLE
Monitors added after Integrating with Home Assistant do not appear as entities

### ISSUE THREAD

**Issue by WolfBrandon** [meichthys/uptime_kuma#68]
After installing Uptime Kuma, adding monitors, and adding the integration, the initial pull of metrics was successful and all monitors appear as entities. However, after adding any new monitor, and even clicking "reload" on the integration, they will not appear as entities unless I remove and re-add the integration.

Logs do not show any errors -- I see the /metrics endpoint being accessed, but the returned monitor_response does not include the newly added monitor. Accessing the /metrics endpoint directly does show the newly added monitor.

Not sure if this is expected behavior, but it defeats the purpose of the "reload" function.

**Comment by WolfBrandon** [comment]
Strange...I just added the exact same monitor and no dice. Fully appreciate this could be something unique to my setup, but I'm not really doing anything radical (synopsis below) -- any advice on where to look besides logs? Here's a quick overview of my setup:

Running HAOS on baremetal
- Home Assistant 2023.8.4
- Supervisor 2023.08.1
- Operating System 10.5
- Frontend 20230802.1 - latest

Running Uptime Kuma on a separate server, in a Docker Container
- v1.23.0 (I will update shortly)
- 40 monitors (38 appear in HA)
- Mix of HTTP and Ping, nothing more

![image](https://github.com/meichthys/uptime_kuma/assets/126610820/fe6228f8-d567-4cf5-9992-4a6ac26565f6)
![image](https://github.com/meichthys/uptime_kuma/assets/126610820/4fcd53bc-4d69-445d-85e9-ecb618f68239)

**Comment by LTTS1991** [comment]
This shh keeps breaking without even showing its broken. It just shows unavailable. I'm setting up this app for the 3rd time now. it's REALLY starting to annoy me

**Comment by LTTS1991** [comment]
If your integration can't even tell the user somethings wrong properly maybe we all should feel free. I have no clue as to how long the integration hasn't worked other than looking at the entity giving me the finger and saying: "unknown". That's your integration not telling me.
