### ISSUE TITLE
Sensors are frequently getting unavailable

### ISSUE THREAD

**Issue by dibyadip-das** [meichthys/uptime_kuma#8]
Sensors are frequently getting unavailable despite being up in Uptime Kuma. Please refer to the screenshot below:

<img src="https://user-images.githubusercontent.com/47345141/178134134-92f70688-1dbd-4d87-aea0-85ad3963dbc8.png" alt="drawing" width="400"/>

HA Details
<html>
<body>

Attribute|Details 
-- | --
Version | core-2022.7.0
Installation Type | Home Assistant OS
Development | false
Supervisor | true
Docker | true
User | root
Virtual Environment | false
Python Version | 3.10.5
Operating System Family | Linux
Operating System Version | 5.15.32-v8
CPU Architecture | aarch64
Timezone | Asia/Kolkata
Configuration Directory | /config

</body>
</html>

Let me know in case more details are required.

**Comment by jayakornk** [comment]
That's odd. It works perfectly find for me. Would it be possible to check the connection between HA and Uptime Kuma.

Maybe you could share info of monitors you are using right now.

**Comment by jayakornk** [comment]
Wait for https://github.com/meichthys/uptime_kuma/pull/9 to merge and create new release (Integration v1.2.1)

**Comment by meichthys** [comment]
Merged and released in v1.2.0 👍
