### ISSUE TITLE
Not being able to establish connection

### ISSUE THREAD

**Issue by x4N70pHyLL** [meichthys/uptime_kuma#80]
Hi,

I just tried to set up the integration but I am not able to connect.

Both Home Assistant and Uptime Kuma are running in a Docker Container in Synology NAS, HA in host network, Uptime Kuma in bridge with port 3001.

I am able to connect from my browser to the local ip of the NAS with 192.168.x.x:3001 as well as to the /metrics with a token.

In HA I am only getting "Request exception for '192.168.x.y:3001/metrics' with - 192.168.x.y:3001/metrics" in the Log. The Integration says "Failed to connect".

Any Ideas?

**Comment by x4N70pHyLL** [comment]
> What version of Uptime Kuma are you using? This may be related to #79

I am using 1.23.3, so it seems not to be related I guess...

**Comment by x4N70pHyLL** [comment]
> I'm not very familiar with different docker network configurations, but i would think the bridge mode should be fine, but there are lots of variables here.
> 
> We've had some other issue reports similar to this, and my usual recommendation is to use a valid HTTPS certificate and a reverse proxy.
> 
> You could also try using "admin" as the username along with the token as the password. Apparently it helped someone here: [#55 (comment)](https://github.com/meichthys/uptime_kuma/issues/55#issuecomment-1661817451)
> 
> You may also find this helpful since DNS is so often an issue: [#19 (comment)](https://github.com/meichthys/uptime_kuma/issues/19#issuecomment-1328336356)

Thanks for the hints, really appreciate it. I am kind of frustrated right now. I double checked, it may be an issue running one container in host and the other in bride mode. To be sure, I both routed the containers together as well as created Uptime Kuma new in host mode just to be sure it is not a Container networking related issue. I tried all options (standard login, admin+token, token only) each with verify certificate and without.

Nothing helped, as I have no idea where to further investigate, seems like I have to give up and use "ping" function within HomeAssistant...

**Comment by ripp2003** [comment]
Hi, try this when using internal kuma server with only ip and no ssl: 
Edit the file config_flow.py
line 48, replace with
```
        async with aiohttp.ClientSession() as session:
            
        uptime_robot_api = UptimeKuma(
            session,
            host:port,
            username,
            password,
            verify_ssl,
        )
```
Now when adding from HA: 
url : http://xxx.xxx.xxx.xxx
port : 3001
usernamle : admin
pass : API pasword (must be created before under kuma)

**Comment by ripp2003** [comment]
Hi, try this when using internal kuma server with only ip and no ssl : 

url : http://xxx.xxx.xxx.xxx
port : 3001
username : admin
pass : API pasword (must be created before under kuma)
dont' use verify ssl

**Comment by x4N70pHyLL** [comment]
> Hi, try this when using internal kuma server with only ip and no ssl :
> 
> url : http://xxx.xxx.xxx.xxx port : 3001 username : admin pass : API pasword (must be created before under kuma) dont' use verify ssl

That helped. Thanks a lot!

**Comment by ripp2003** [comment]
I had the same problem and that make me crazy 😀

**Comment by ianpogi5** [comment]
> Hi, try this when using internal kuma server with only ip and no ssl :
> 
> url : http://xxx.xxx.xxx.xxx port : 3001 username : admin pass : API pasword (must be created before under kuma) dont' use verify ssl

can someone put this in the `README`?
